name: imgai
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.18.6 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  dio: ^4.0.0
  path_provider: ^2.0.5

  cupertino_icons: ^1.0.2
  share: ^2.0.4
  url_launcher: ^6.2.2
  font_awesome_flutter: ^9.0.0

  # Other dependencies go here

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/generatePage/Slide1.jpg
    - assets/generatePage/Slide2.jpg
    - assets/generatePage/Slide3.jpg

